import { api, getCurrentUser } from '../js/api.js'
import { escapeHtml, money, setBusy } from '../js/ui.js'

const route = location.pathname.replace(/\/+$/, '').split('/').pop() || 'index'
const page = (route === 'admin' ? 'index' : route).replace('admin_', '').replace('.html', '') || 'index'
const endpoint = { products: 'products', customers: 'customers' }[page] || 'workspace'
if (endpoint === 'workspace' && page !== 'index') location.replace('/admin/')
const customer = (o) => o.profiles?.display_name || o.profiles?.email || 'Customer'
const summary = (o) => (o.order_items || []).map(i => `${i.product_name} × ${i.quantity}`).join(', ') || 'Order items'
const date = (value) => new Date(value).toLocaleDateString('en-MY', { day: 'numeric', month: 'short' })
const paymentState = (o) => o.payment_status || o.payments?.[0]?.status || 'paid'
const state = (o) => o.shipping_status === 'pending' ? 'Ready to prepare' : o.shipping_status === 'preparing' ? 'In preparation' : o.shipping_status === 'shipped' ? 'Out for delivery' : o.shipping_status === 'delivered' ? 'Delivered' : o.status === 'cancelled' ? 'Cancelled' : paymentState(o) === 'pending' ? 'Waiting for payment' : 'Confirmed'
const action = (o) => o.shipping_status === 'pending' ? ['Start preparing', 'preparing', 'processing'] : o.shipping_status === 'preparing' ? ['Mark ready to ship', 'shipped', 'processing'] : o.shipping_status === 'shipped' ? ['Mark delivered', 'delivered', 'completed'] : null

function row(o, selected) { return `<button type="button" data-open-order="${escapeHtml(o.id)}" class="pb-order-row ${selected ? 'is-selected' : ''}"><span class="pb-order-number">#${escapeHtml(o.id.slice(0, 8))}</span><span><b>${escapeHtml(customer(o))}</b><small>${escapeHtml(summary(o))}</small></span><span><b>${money(o.total_cents)}</b><small>${escapeHtml(state(o))}</small></span><span class="pb-row-action">Open</span></button>` }
function detail(o) {
  if (!o) return `<aside class="pb-order-detail"><p class="pb-kicker">Select an order</p><h2 class="pb-display">Your next task will appear here.</h2></aside>`
  const next = action(o), payment = o.payments?.[0]
  return `<aside class="pb-order-detail" aria-live="polite"><div class="pb-detail-top"><div><p class="pb-kicker">Order #${escapeHtml(o.id.slice(0, 8))}</p><h2 class="pb-display">${escapeHtml(customer(o))}</h2><p>${money(o.total_cents)} · placed ${date(o.created_at)}</p></div><span class="pb-status">${escapeHtml(state(o))}</span></div><div class="pb-detail-section"><h3>Order</h3><ul class="pb-detail-items">${(o.order_items || []).map(i => `<li><span>${escapeHtml(i.product_name)} <small>× ${i.quantity}</small></span><b>${money(i.unit_price_cents * i.quantity)}</b></li>`).join('') || '<li>Items unavailable</li>'}</ul></div><div class="pb-detail-section pb-detail-two"><div><h3>Delivery</h3><p>${escapeHtml([o.shipping_name, o.address1, o.address2, o.city, o.postal_code, o.country].filter(Boolean).join(', '))}</p></div><div><h3>Payment</h3><p><span class="pb-status ${paymentState(o) === 'paid' ? 'paid' : ''}">${escapeHtml(paymentState(o))}</span><br>${escapeHtml(payment?.receipt_number || 'Demo receipt')}</p></div></div><div class="pb-order-timeline"><span class="is-done">Paid</span><span class="${['preparing','shipped','delivered'].includes(o.shipping_status) ? 'is-done' : ''}">Preparing</span><span class="${['shipped','delivered'].includes(o.shipping_status) ? 'is-done' : ''}">Shipped</span><span class="${o.shipping_status === 'delivered' ? 'is-done' : ''}">Delivered</span></div>${next ? `<button class="pb-button pb-detail-action" data-advance-order="${escapeHtml(o.id)}" data-shipping="${next[1]}" data-status="${next[2]}">${next[0]}</button>` : '<p class="pb-detail-finished">This order is complete.</p>'}</aside>`
}
function workspace(data, selectedId, filter = 'prepare') {
  const orders = data.orders || [], queues = { payment: orders.filter(o => paymentState(o) === 'pending'), prepare: orders.filter(o => paymentState(o) === 'paid' && ['pending', 'preparing'].includes(o.shipping_status)), delivery: orders.filter(o => ['shipped', 'delivered'].includes(o.shipping_status)) }, active = queues[filter] || queues.prepare, selected = orders.find(o => o.id === selectedId) || active[0] || orders[0]
  const title = filter === 'payment' ? 'Waiting for payment' : filter === 'delivery' ? 'In delivery' : 'Ready to prepare'
  return `<div class="pb-admin-layout"><section><div class="pb-admin-intro"><div><p class="pb-kicker">Good things rise daily</p><h1 class="pb-display">Today at the bakery</h1><p>Move each order from payment to doorstep with a clear next step.</p></div><div class="pb-admin-counts"><span><b>${orders.length}</b>Orders</span><span><b>${queues.prepare.length}</b>To prepare</span><span><b>${queues.delivery.filter(o => o.shipping_status === 'shipped').length}</b>Out for delivery</span></div></div><nav class="pb-queue-tabs" aria-label="Order queues"><button data-filter="prepare" class="${filter === 'prepare' ? 'is-active' : ''}">To prepare <b>${queues.prepare.length}</b></button><button data-filter="payment" class="${filter === 'payment' ? 'is-active' : ''}">Needs payment <b>${queues.payment.length}</b></button><button data-filter="delivery" class="${filter === 'delivery' ? 'is-active' : ''}">In delivery <b>${queues.delivery.length}</b></button></nav><section class="pb-queue"><div class="pb-queue-head"><div><p class="pb-kicker">${filter === 'payment' ? 'Follow up' : filter === 'delivery' ? 'Keep an eye on' : 'Make next'}</p><h2>${title}</h2></div><span>${active.length} orders</span></div><div class="pb-order-list">${active.length ? active.map(o => row(o, o.id === selected?.id)).join('') : '<p class="pb-admin-empty">Nothing needs attention here.</p>'}</div></section>${data.lowStock?.length ? `<section class="pb-stock-note"><div><p class="pb-kicker">Inventory check</p><b>Low stock</b><p>${data.lowStock.map(p => `${escapeHtml(p.name)} (${p.stock} left)`).join(' · ')}</p></div><a href="/admin/products/" class="pb-button alt">View products</a></section>` : ''}</section>${detail(selected)}</div>`
}
function products(items) { return `<div class="pb-support-page"><p class="pb-kicker">Bakery catalogue</p><h1 class="pb-display">Products</h1><div class="pb-product-admin-list">${items.map(p => `<form data-product-id="${escapeHtml(p.id)}"><div><b>${escapeHtml(p.name)}</b><small>${escapeHtml(p.category)}</small></div><label>Price<input name="price" type="number" min="0" step="0.01" value="${(p.price_cents / 100).toFixed(2)}"></label><label>Stock<input name="stock" type="number" min="0" value="${p.stock}"></label><button class="pb-button">Save</button></form>`).join('')}</div></div>` }
function customers(items) { return `<div class="pb-support-page"><p class="pb-kicker">People we bake for</p><h1 class="pb-display">Customers</h1><div class="pb-customer-list">${items.map(p => `<div><b>${escapeHtml(p.display_name || 'Customer')}</b><span>${escapeHtml(p.email)}</span><small>Joined ${date(p.created_at)}</small></div>`).join('')}</div></div>` }
async function load() {
  const user = await getCurrentUser(); if (!user) return location.href = `/auth/login/?next=${encodeURIComponent(location.pathname)}`
  let data; try { data = await api(`/api/admin/${endpoint}`) } catch (e) { document.body.innerHTML = `<main class="pb-main"><h1 class="pb-display">Could not load the admin portal</h1><p>${escapeHtml(e.message)}</p><button class="pb-button" onclick="location.reload()">Try again</button></main>`; return }
  let selectedId, filter = 'prepare'
  const render = () => { const body = endpoint === 'workspace' ? workspace(data, selectedId, filter) : endpoint === 'products' ? products(data.products || []) : customers(data.customers || []); document.body.innerHTML = `<header class="pb-admin-header"><a class="pb-admin-brand" href="/admin/"><img src="/assets/petitbakery-logo.png" alt="PetitBakery"><span>PetitBakery<small>Bakery admin</small></span></a><nav><a href="/">Shop</a><a href="/admin/" ${endpoint === 'workspace' ? 'aria-current="page"' : ''}>Orders</a><a href="/admin/products/" ${endpoint === 'products' ? 'aria-current="page"' : ''}>Products</a><a href="/admin/customers/" ${endpoint === 'customers' ? 'aria-current="page"' : ''}>Customers</a></nav><a class="pb-admin-user" href="/account/">${escapeHtml(user.displayName)}<small>Bakery admin</small></a></header><main class="pb-admin-main">${body}</main>`; bind() }
  const bind = () => { document.querySelectorAll('[data-open-order]').forEach(b => b.onclick = () => { selectedId = b.dataset.openOrder; render() }); document.querySelectorAll('[data-filter]').forEach(b => b.onclick = () => { filter = b.dataset.filter; selectedId = undefined; render() }); document.querySelector('[data-advance-order]')?.addEventListener('click', async e => { const b = e.currentTarget; setBusy(b, true); try { const { order } = await api(`/api/admin/orders/${encodeURIComponent(b.dataset.advanceOrder)}`, { method: 'PATCH', body: JSON.stringify({ shipping_status: b.dataset.shipping, status: b.dataset.status }) }); const index = data.orders.findIndex(o => o.id === order.id); data.orders[index] = { ...data.orders[index], ...order }; selectedId = order.id; render() } catch (error) { b.textContent = error.message; setBusy(b, false) } }); document.querySelectorAll('[data-product-id]').forEach(form => form.onsubmit = async e => { e.preventDefault(); const fields = Object.fromEntries(new FormData(form)), b = form.querySelector('button'); setBusy(b, true); try { await api(`/api/admin/products/${form.dataset.productId}`, { method: 'PATCH', body: JSON.stringify({ price_cents: Math.round(Number(fields.price) * 100), stock: Number(fields.stock) }) }); b.textContent = 'Saved' } catch (error) { b.textContent = error.message } finally { setBusy(b, false) } }) }
  render()
}
load().catch(e => { document.body.innerHTML = `<main class="pb-main"><h1 class="pb-display">Admin page unavailable</h1><p>${escapeHtml(e.message)}</p></main>` })
